name: test

on: [push]

jobs:
  test-ubuntu:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tutorial: ["EX2_Dahlquist"]
        mpi_bin: ["/usr/bin/"]
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Setup mpich
        run: |
          sudo apt-get update
          sudo apt-get -y install mpich
      - name: Compile
        run: |
          cd examples/${{ matrix.tutorial }}
          make MPI_BIN=${{ matrix.mpi_bin }} GCC10=TRUE
      - name: Run sequential
        run: ./tests/run_example.sh EX2_Dahlquist
      - name: Run parallel
        run: ./tests/run_example.sh -n 4 EX2_Dahlquist
      - name: Test
        run: |
          make MPI_BIN=${{ matrix.mpi_bin }} -C LibPFASST/Tutorials/${{ matrix.tutorial }}
          ./tests/ex2_test.sh
