name: CI

on: [push]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Setup mpich
        run: |
          sudo apt-get update
          sudo apt-get -y install mpich
      - name: Compile and run 
        run: |
          make all
          mpiexec build/cmain
