name: test

on: [push]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Setup mpich
        run: |
          sudo apt-get update
          sudo apt-get -y install mpich
      - name: Compile and run 
        run: |
          make MPICH_BIN=/usr/bin
          mpiexec ./cmain probin.nml
          mpiexec ./cmain sdc.nml
          mpiexec ./cmain multi_level.nml
          mpiexec ./cmain pipeline.nml
      - name: Run parallel
        run: |
          mpiexec -n 4 ./cmain probin.nml
          mpiexec -n 4 ./cmain sdc.nml
          mpiexec -n 4 ./cmain multi_level.nml
          mpiexec -n 4 ./cmain pipeline.nml
      - name: Test
        run: |
          make -C LibPFASST/Tutorials/EX2_Dahlquist/
          ./tests/ex2_compare.sh probin.nml
          ./tests/ex2_compare.sh sdc.nml
          ./tests/ex2_compare.sh multi_level.nml
          ./tests/ex2_compare.sh pipeline.nml